version: '3.9'
services:
  testserver-sin:
    build: .
    networks:
      sin:
        ipv4_address: 192.168.101.20
  testserver-iad:
    build: .
    networks:
      iad:
        ipv4_address: 192.168.102.20
  testserver-cdg:
    build: .
    networks:
      cdg:
        ipv4_address: 192.168.103.20
networks:
  sin:
    ipam:
      driver: default
      config:
        - subnet: '192.168.101.0/24'
  iad:
    ipam:
      driver: default
      config:
        - subnet: '192.168.102.0/24'
  cdg:
    ipam:
      driver: default
      config:
        - subnet: '192.168.103.0/24'
